import { Device, DeviceCategory, InterfaceType } from '../types/device'

const now = new Date().toISOString()

export const seedDevices: Device[] = [
  // ===== 核心板类 =====
  {
    id: 'BOARD-20260626-001',
    name: 'ESP32-S3 N16R8 开发板',
    category: DeviceCategory.BOARD,
    subCategory: '开发板',
    coreModel: 'ESP32-S3',
    manufacturer: 'Espressif',
    interfaces: [InterfaceType.USB, InterfaceType.UART, InterfaceType.SPI, InterfaceType.I2C, InterfaceType.WIFI, InterfaceType.BLUETOOTH],
    tags: ['ESP32开发板', '微控制器板', 'Arduino', '开发板'],
    purpose: '主控核心',
    project: '通用开发平台',
    shelfNumber: 'A-01',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'BOARD-20260626-019',
    name: 'ESP32-S3-WROOM-1 芯片模组',
    category: DeviceCategory.BOARD,
    subCategory: '核心板',
    coreModel: 'ESP32-S3',
    manufacturer: 'Espressif',
    interfaces: [InterfaceType.UART, InterfaceType.SPI, InterfaceType.I2C, InterfaceType.WIFI, InterfaceType.BLUETOOTH],
    tags: ['芯片模组', 'ESP32-S3模组', 'WiFi模块', '蓝牙模块'],
    shelfNumber: 'A-19',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'BOARD-20260626-002',
    name: 'ESP32-WROOM-32E 芯片模组',
    category: DeviceCategory.BOARD,
    subCategory: '核心板',
    coreModel: 'ESP32-D0WD-V3',
    manufacturer: 'Espressif',
    interfaces: [InterfaceType.UART, InterfaceType.SPI, InterfaceType.I2C, InterfaceType.WIFI, InterfaceType.BLUETOOTH],
    tags: ['芯片模组', 'ESP32模组', 'WiFi模块', '蓝牙模块'],
    shelfNumber: 'A-02',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'BOARD-20260626-003',
    name: 'Nano V3.0 开发板 (CH340G, ATMEGA328P, TYPE-C)',
    category: DeviceCategory.BOARD,
    subCategory: '开发板',
    coreModel: 'ATMEGA328P',
    manufacturer: 'Arduino',
    interfaces: [InterfaceType.USB, InterfaceType.UART, InterfaceType.SPI, InterfaceType.I2C, InterfaceType.GPIO, InterfaceType.ADC, InterfaceType.PWM],
    tags: ['开发板', '微控制器板', 'Arduino'],
    purpose: '基础控制',
    project: 'Arduino项目',
    shelfNumber: 'A-03',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'BOARD-20260626-004',
    name: 'ESP8266 NodeMcu V3 开发板 (CH340, TYPE-C)',
    category: DeviceCategory.BOARD,
    subCategory: '开发板',
    coreModel: 'ESP8266',
    manufacturer: 'Espressif',
    interfaces: [InterfaceType.UART, InterfaceType.SPI, InterfaceType.I2C, InterfaceType.WIFI, InterfaceType.GPIO],
    tags: ['开发板', 'Arduino'],
    shelfNumber: 'A-04',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'BOARD-20260626-005',
    name: 'BW16 UNO 开发板 (RTL8720DN, 双频WiFi+蓝牙)',
    category: DeviceCategory.BOARD,
    subCategory: '开发板',
    coreModel: 'RTL8720DN',
    manufacturer: 'Realtek',
    interfaces: [InterfaceType.UART, InterfaceType.SPI, InterfaceType.I2C, InterfaceType.WIFI, InterfaceType.BLUETOOTH, InterfaceType.GPIO],
    tags: ['开发板', '双频模组'],
    shelfNumber: 'A-05',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'BOARD-20260626-006',
    name: 'ESP32E 开发板 (ESP WROOM 32, WiFi+蓝牙, TYPE-C)',
    category: DeviceCategory.BOARD,
    subCategory: '开发板',
    coreModel: 'ESP32',
    manufacturer: 'Espressif',
    interfaces: [InterfaceType.USB, InterfaceType.UART, InterfaceType.SPI, InterfaceType.I2C, InterfaceType.WIFI, InterfaceType.BLUETOOTH, InterfaceType.GPIO],
    tags: ['开发板'],
    purpose: '通用开发',
    project: '物联网项目',
    shelfNumber: 'A-06',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'BOARD-20260626-007',
    name: 'STM32F103C8T6 最小系统板',
    category: DeviceCategory.BOARD,
    subCategory: '核心板',
    coreModel: 'STM32F103C8T6',
    manufacturer: 'ST',
    interfaces: [InterfaceType.UART, InterfaceType.SPI, InterfaceType.I2C, InterfaceType.CAN, InterfaceType.GPIO, InterfaceType.ADC, InterfaceType.PWM],
    tags: ['芯片模组', '微控制器板', 'ARM开发板'],
    purpose: '工业控制',
    project: '自动化项目',
    shelfNumber: 'A-07',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'BOARD-20260626-008',
    name: 'STM32F407VET6 开发板',
    category: DeviceCategory.BOARD,
    subCategory: '开发板',
    coreModel: 'STM32F407VET6',
    manufacturer: 'ST',
    interfaces: [InterfaceType.USB, InterfaceType.UART, InterfaceType.SPI, InterfaceType.I2C, InterfaceType.CAN, InterfaceType.ETHERNET, InterfaceType.GPIO],
    tags: ['ARM开发板', '开发板'],
    purpose: '高性能控制',
    project: '嵌入式项目',
    shelfNumber: 'A-08',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'BOARD-20260626-009',
    name: 'Raspberry Pi 4 Model B',
    category: DeviceCategory.BOARD,
    subCategory: '树莓派',
    coreModel: 'BCM2711',
    manufacturer: 'Raspberry Pi',
    interfaces: [InterfaceType.USB, InterfaceType.UART, InterfaceType.SPI, InterfaceType.I2C, InterfaceType.GPIO, InterfaceType.ETHERNET, InterfaceType.BLUETOOTH, InterfaceType.WIFI],
    tags: ['树莓派', '单板计算机'],
    purpose: '单板计算机',
    project: '服务器/桌面项目',
    shelfNumber: 'A-09',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'BOARD-20260626-010',
    name: 'ESP32-C3 开发板 (RISC-V, WiFi+蓝牙)',
    category: DeviceCategory.BOARD,
    subCategory: '开发板',
    coreModel: 'ESP32-C3',
    manufacturer: 'Espressif',
    interfaces: [InterfaceType.USB, InterfaceType.UART, InterfaceType.SPI, InterfaceType.I2C, InterfaceType.WIFI, InterfaceType.BLUETOOTH, InterfaceType.GPIO],
    tags: ['开发板', 'RISC-V开发板'],
    shelfNumber: 'A-10',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'BOARD-20260626-011',
    name: 'STM32F411CEU6 开发板 (WeAct Studio)',
    category: DeviceCategory.BOARD,
    subCategory: '开发板',
    coreModel: 'STM32F411CEU6',
    manufacturer: 'ST',
    interfaces: [InterfaceType.USB, InterfaceType.UART, InterfaceType.SPI, InterfaceType.I2C, InterfaceType.GPIO, InterfaceType.ADC, InterfaceType.PWM],
    tags: ['ARM开发板', '开发板'],
    purpose: '嵌入式开发',
    project: '无人机飞控',
    shelfNumber: 'A-11',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'BOARD-20260626-012',
    name: 'Arduino Mega 2560 开发板 (ATMEGA2560-16AU)',
    category: DeviceCategory.BOARD,
    subCategory: '开发板',
    coreModel: 'ATMEGA2560',
    manufacturer: 'Arduino',
    interfaces: [InterfaceType.USB, InterfaceType.UART, InterfaceType.SPI, InterfaceType.I2C, InterfaceType.GPIO, InterfaceType.ADC, InterfaceType.PWM],
    tags: ['开发板', '微控制器板', 'Arduino'],
    purpose: '3D打印机主控',
    project: '3D打印机项目',
    shelfNumber: 'A-12',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'BOARD-20260626-013',
    name: '树莓派 Zero 2 W (RP3A0, 512MB RAM)',
    category: DeviceCategory.BOARD,
    subCategory: '核心板',
    coreModel: 'RP3A0',
    manufacturer: 'Raspberry Pi',
    interfaces: [InterfaceType.USB, InterfaceType.UART, InterfaceType.SPI, InterfaceType.I2C, InterfaceType.GPIO, InterfaceType.WIFI, InterfaceType.BLUETOOTH],
    tags: ['树莓派', '嵌入式Linux', 'WiFi模块', '蓝牙模块'],
    purpose: '嵌入式Linux服务器',
    project: '远程监控项目',
    shelfNumber: 'A-13',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'BOARD-20260626-014',
    name: 'Artix-7 XC7A35T FPGA 开发板',
    category: DeviceCategory.BOARD,
    subCategory: '开发板',
    coreModel: 'XC7A35T',
    manufacturer: 'Xilinx',
    interfaces: [InterfaceType.UART, InterfaceType.SPI, InterfaceType.I2C, InterfaceType.GPIO, InterfaceType.JTAG, InterfaceType.SWD],
    tags: ['FPGA开发板', '可编程逻辑', 'JTAG调试', '开发板'],
    purpose: '数字逻辑验证',
    project: 'FPGA学习项目',
    shelfNumber: 'A-14',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'BOARD-20260626-015',
    name: '西门子 S7-1200 PLC 模块 (CPU 1212C)',
    category: DeviceCategory.BOARD,
    subCategory: '核心板',
    coreModel: 'CPU 1212C',
    manufacturer: 'Siemens',
    interfaces: [InterfaceType.ETHERNET, InterfaceType.GPIO, InterfaceType.RS485],
    tags: ['PLC模块', '工业控制', '以太网模块'],
    purpose: '工业自动化控制',
    project: '生产线项目',
    shelfNumber: 'A-15',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'BOARD-20260626-016',
    name: 'ESP32-C6-DevKitC-1 开发板 (WiFi6+BLE5+Thread)',
    category: DeviceCategory.BOARD,
    subCategory: '开发板',
    coreModel: 'ESP32-C6',
    manufacturer: 'Espressif',
    interfaces: [InterfaceType.USB, InterfaceType.UART, InterfaceType.SPI, InterfaceType.I2C, InterfaceType.WIFI, InterfaceType.BLUETOOTH, InterfaceType.GPIO],
    tags: ['ESP32开发板', 'WiFi6模块', '蓝牙模块', 'Thread协议', '开发板'],
    purpose: '物联网边缘计算',
    project: '智能家居项目',
    shelfNumber: 'A-16',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'BOARD-20260626-017',
    name: 'STC89C52RC 单片机最小系统板',
    category: DeviceCategory.BOARD,
    subCategory: '开发板',
    coreModel: 'STC89C52RC',
    manufacturer: 'STC',
    interfaces: [InterfaceType.UART, InterfaceType.GPIO, InterfaceType.SPI],
    tags: ['51单片机', '微控制器板', '开发板'],
    purpose: '基础教学实验',
    project: '单片机教学项目',
    shelfNumber: 'A-17',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'BOARD-20260626-018',
    name: 'ESP32-H2-DevKitM-1 开发板 (Matter协议, BLE+ZigBee)',
    category: DeviceCategory.BOARD,
    subCategory: '开发板',
    coreModel: 'ESP32-H2',
    manufacturer: 'Espressif',
    interfaces: [InterfaceType.USB, InterfaceType.UART, InterfaceType.SPI, InterfaceType.I2C, InterfaceType.BLUETOOTH, InterfaceType.GPIO],
    tags: ['ESP32开发板', '蓝牙模块', 'ZigBee模块', 'Matter协议', '开发板'],
    purpose: '智能家居网关',
    project: 'Matter兼容项目',
    shelfNumber: 'A-18',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'BOARD-20260626-020',
    name: 'Raspberry Pi 3 Model B+',
    category: DeviceCategory.BOARD,
    subCategory: '树莓派',
    coreModel: 'BCM2837B0',
    manufacturer: 'Raspberry Pi',
    interfaces: [InterfaceType.USB, InterfaceType.UART, InterfaceType.SPI, InterfaceType.I2C, InterfaceType.GPIO, InterfaceType.ETHERNET, InterfaceType.BLUETOOTH, InterfaceType.WIFI],
    tags: ['树莓派', '单板计算机'],
    purpose: '嵌入式服务器',
    project: '网络服务器项目',
    shelfNumber: 'A-20',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'BOARD-20260626-021',
    name: '三菱 FX3U-16MR PLC 模块',
    category: DeviceCategory.BOARD,
    subCategory: 'PLC模块',
    coreModel: 'FX3U-16MR',
    manufacturer: 'Mitsubishi',
    interfaces: [InterfaceType.UART, InterfaceType.GPIO, InterfaceType.RS485],
    tags: ['PLC模块', '工业控制', '可编程控制器'],
    purpose: '工业自动化控制',
    project: '自动化生产线',
    shelfNumber: 'A-21',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'BOARD-20260626-022',
    name: '欧姆龙 CP1E-E20DR PLC 模块',
    category: DeviceCategory.BOARD,
    subCategory: 'PLC模块',
    coreModel: 'CP1E-E20DR',
    manufacturer: 'Omron',
    interfaces: [InterfaceType.UART, InterfaceType.GPIO, InterfaceType.RS232],
    tags: ['PLC模块', '工业控制', '可编程控制器'],
    purpose: '小型自动化控制',
    project: '分拣控制系统',
    shelfNumber: 'A-22',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },

  // ===== 传感器类 =====
  {
    id: 'SENSOR-20260626-001',
    name: 'DHT11温湿度模块',
    category: DeviceCategory.SENSOR,
    subCategory: '温度传感器',
    coreModel: 'DHT11',
    manufacturer: '奥松',
    interfaces: [InterfaceType.GPIO],
    tags: ['湿度传感器'],
    purpose: '温湿度监测',
    project: '环境监测系统',
    shelfNumber: 'B-01',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-002',
    name: 'SU-03T 语音识别模块',
    category: DeviceCategory.SENSOR,
    subCategory: '语音识别模块',
    coreModel: 'SU-03T',
    manufacturer: '安信可',
    interfaces: [InterfaceType.UART],
    tags: ['串口通信模块'],
    purpose: '语音识别与控制',
    project: '智能语音助手',
    shelfNumber: 'B-02',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-003',
    name: 'MQ-135空气质量传感器模块',
    category: DeviceCategory.SENSOR,
    subCategory: '气体传感器',
    coreModel: 'MQ-135',
    manufacturer: '炜盛',
    interfaces: [InterfaceType.ADC],
    tags: ['空气质量传感器', '有害气体检测'],
    shelfNumber: 'B-03',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-004',
    name: 'INMP441全向麦克风模块',
    category: DeviceCategory.SENSOR,
    subCategory: '声音传感器',
    coreModel: 'INMP441',
    manufacturer: 'InvenSense',
    interfaces: [InterfaceType.I2S],
    tags: ['麦克风模块', 'MEMS麦克风'],
    shelfNumber: 'B-04',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-005',
    name: 'MAX9814麦克风放大器模块',
    category: DeviceCategory.SENSOR,
    subCategory: '声音传感器',
    coreModel: 'MAX9814',
    manufacturer: 'Maxim',
    interfaces: [InterfaceType.ADC],
    tags: ['音频放大器', '麦克风模块'],
    shelfNumber: 'B-05',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-006',
    name: 'LU6288 文本转语音模块',
    category: DeviceCategory.SENSOR,
    subCategory: '语音识别模块',
    coreModel: 'LU6288',
    manufacturer: '宇音天下',
    interfaces: [InterfaceType.UART],
    tags: ['语音合成模块', '文本转语音'],
    shelfNumber: 'B-06',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-007',
    name: 'MAX30102心率血氧传感器模块',
    category: DeviceCategory.SENSOR,
    subCategory: '心率传感器',
    coreModel: 'MAX30102',
    manufacturer: 'Maxim',
    interfaces: [InterfaceType.I2C],
    tags: ['光学传感器', '血氧传感器'],
    shelfNumber: 'B-07',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-008',
    name: '触摸传感器模块 (轻触开关, 1路)',
    category: DeviceCategory.SENSOR,
    subCategory: '触摸传感器',
    coreModel: 'TTP223',
    manufacturer: '普通',
    interfaces: [InterfaceType.GPIO],
    tags: ['触摸模块'],
    shelfNumber: 'B-08',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-009',
    name: '3144 霍尔传感器模块 (电机测速/计数)',
    category: DeviceCategory.SENSOR,
    subCategory: '霍尔传感器',
    coreModel: '3144',
    manufacturer: 'Allegro',
    interfaces: [InterfaceType.GPIO],
    tags: ['磁性传感器'],
    shelfNumber: 'B-09',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-010',
    name: '土壤湿度传感器模块',
    category: DeviceCategory.SENSOR,
    subCategory: '土壤湿度传感器',
    coreModel: 'LM393',
    manufacturer: '普通',
    interfaces: [InterfaceType.ADC],
    tags: ['模拟传感器'],
    shelfNumber: 'B-10',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-011',
    name: '双轴 XY 摇杆模块 (PS2游戏摇杆, JoyStick)',
    category: DeviceCategory.SENSOR,
    subCategory: '其他传感器',
    coreModel: 'PS2',
    manufacturer: '普通',
    interfaces: [InterfaceType.ADC],
    tags: ['输入模块', '模拟传感器'],
    shelfNumber: 'B-11',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-012',
    name: 'GY-521 MPU6050 六轴传感器模块',
    category: DeviceCategory.SENSOR,
    subCategory: '陀螺仪传感器',
    coreModel: 'MPU6050',
    manufacturer: 'InvenSense',
    interfaces: [InterfaceType.I2C],
    tags: ['加速度传感器', '姿态检测'],
    shelfNumber: 'B-12',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-013',
    name: 'OV7670 摄像头模块 (STM32驱动, 50万像素)',
    category: DeviceCategory.SENSOR,
    subCategory: '光学传感器',
    coreModel: 'OV7670',
    manufacturer: 'OmniVision',
    interfaces: [InterfaceType.SPI],
    tags: ['摄像头模块'],
    shelfNumber: 'B-13',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-014',
    name: 'DHT22 高精度温湿度传感器模块',
    category: DeviceCategory.SENSOR,
    subCategory: '温度传感器',
    coreModel: 'DHT22',
    manufacturer: '奥松',
    interfaces: [InterfaceType.GPIO],
    tags: ['湿度传感器', '高精度'],
    shelfNumber: 'B-14',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-015',
    name: 'DS18B20 防水温度传感器',
    category: DeviceCategory.SENSOR,
    subCategory: '温度传感器',
    coreModel: 'DS18B20',
    manufacturer: 'Dallas',
    interfaces: [InterfaceType.GPIO],
    tags: ['防水传感器', '数字传感器'],
    shelfNumber: 'B-15',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-016',
    name: 'SYN6288 语音合成模块',
    category: DeviceCategory.SENSOR,
    subCategory: '语音识别模块',
    coreModel: 'SYN6288',
    manufacturer: '宇音天下',
    interfaces: [InterfaceType.UART],
    tags: ['语音合成模块', '文本转语音'],
    shelfNumber: 'B-16',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-017',
    name: 'MQ-2 烟雾传感器模块',
    category: DeviceCategory.SENSOR,
    subCategory: '气体传感器',
    coreModel: 'MQ-2',
    manufacturer: '炜盛',
    interfaces: [InterfaceType.ADC],
    tags: ['烟雾传感器', '可燃气体检测'],
    shelfNumber: 'B-17',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-018',
    name: 'MQ-7 一氧化碳传感器模块',
    category: DeviceCategory.SENSOR,
    subCategory: '气体传感器',
    coreModel: 'MQ-7',
    manufacturer: '炜盛',
    interfaces: [InterfaceType.ADC],
    tags: ['有害气体检测', '一氧化碳检测'],
    shelfNumber: 'B-18',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-019',
    name: 'MAX4466 麦克风放大器模块',
    category: DeviceCategory.SENSOR,
    subCategory: '声音传感器',
    coreModel: 'MAX4466',
    manufacturer: 'Maxim',
    interfaces: [InterfaceType.ADC],
    tags: ['音频放大器', '麦克风模块'],
    shelfNumber: 'B-19',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-020',
    name: 'Pulse Sensor 心率传感器模块',
    category: DeviceCategory.SENSOR,
    subCategory: '心率传感器',
    coreModel: 'Pulse Sensor',
    manufacturer: '普通',
    interfaces: [InterfaceType.ADC],
    tags: ['光学传感器', '生物传感器'],
    shelfNumber: 'B-20',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-021',
    name: 'AD8232 心电传感器模块',
    category: DeviceCategory.SENSOR,
    subCategory: '心率传感器',
    coreModel: 'AD8232',
    manufacturer: 'ADI',
    interfaces: [InterfaceType.ADC],
    tags: ['生物传感器', '医疗传感器'],
    shelfNumber: 'B-21',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-022',
    name: '电容式触摸传感器模块 (TTP226, 8路)',
    category: DeviceCategory.SENSOR,
    subCategory: '触摸传感器',
    coreModel: 'TTP226',
    manufacturer: '普通',
    interfaces: [InterfaceType.GPIO],
    tags: ['触摸模块', '多通道'],
    shelfNumber: 'B-22',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-023',
    name: '电感式触摸传感器模块',
    category: DeviceCategory.SENSOR,
    subCategory: '触摸传感器',
    coreModel: 'LDC1000',
    manufacturer: 'TI',
    interfaces: [InterfaceType.SPI],
    tags: ['触摸模块', '电感式'],
    shelfNumber: 'B-23',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-024',
    name: 'A3144E 霍尔效应传感器 (开门检测)',
    category: DeviceCategory.SENSOR,
    subCategory: '霍尔传感器',
    coreModel: 'A3144E',
    manufacturer: 'Allegro',
    interfaces: [InterfaceType.GPIO],
    tags: ['磁性传感器', '开关检测'],
    shelfNumber: 'B-24',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-025',
    name: 'US1881 双极霍尔传感器',
    category: DeviceCategory.SENSOR,
    subCategory: '霍尔传感器',
    coreModel: 'US1881',
    manufacturer: 'Melexis',
    interfaces: [InterfaceType.GPIO],
    tags: ['磁性传感器', '双极'],
    shelfNumber: 'B-25',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-026',
    name: '电容式土壤湿度传感器',
    category: DeviceCategory.SENSOR,
    subCategory: '土壤湿度传感器',
    coreModel: 'TLC555',
    manufacturer: '普通',
    interfaces: [InterfaceType.ADC],
    tags: ['模拟传感器', '耐腐蚀'],
    shelfNumber: 'B-26',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-027',
    name: '电阻式土壤湿度传感器 (不锈钢探针)',
    category: DeviceCategory.SENSOR,
    subCategory: '土壤湿度传感器',
    coreModel: 'LM393',
    manufacturer: '普通',
    interfaces: [InterfaceType.ADC],
    tags: ['模拟传感器'],
    shelfNumber: 'B-27',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-028',
    name: '火焰传感器模块 (红外探测)',
    category: DeviceCategory.SENSOR,
    subCategory: '其他传感器',
    coreModel: 'LM393',
    manufacturer: '普通',
    interfaces: [InterfaceType.GPIO, InterfaceType.ADC],
    tags: ['火焰传感器', '红外传感器'],
    shelfNumber: 'B-28',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-029',
    name: '雨水/雨滴传感器模块',
    category: DeviceCategory.SENSOR,
    subCategory: '其他传感器',
    coreModel: 'LM393',
    manufacturer: '普通',
    interfaces: [InterfaceType.GPIO, InterfaceType.ADC],
    tags: ['雨滴传感器', '液体检测'],
    shelfNumber: 'B-29',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-030',
    name: 'L3G4200D 三轴陀螺仪模块',
    category: DeviceCategory.SENSOR,
    subCategory: '陀螺仪传感器',
    coreModel: 'L3G4200D',
    manufacturer: 'ST',
    interfaces: [InterfaceType.SPI, InterfaceType.I2C],
    tags: ['角度传感器'],
    shelfNumber: 'B-30',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-031',
    name: 'MPU9250 九轴传感器模块',
    category: DeviceCategory.SENSOR,
    subCategory: '陀螺仪传感器',
    coreModel: 'MPU9250',
    manufacturer: 'InvenSense',
    interfaces: [InterfaceType.SPI, InterfaceType.I2C],
    tags: ['加速度传感器', '磁力传感器', '姿态检测'],
    shelfNumber: 'B-31',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-032',
    name: 'TCS34725 颜色传感器模块',
    category: DeviceCategory.SENSOR,
    subCategory: '光学传感器',
    coreModel: 'TCS34725',
    manufacturer: 'AMS',
    interfaces: [InterfaceType.I2C],
    tags: ['颜色传感器'],
    shelfNumber: 'B-32',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-033',
    name: 'BH1750 光照强度传感器',
    category: DeviceCategory.SENSOR,
    subCategory: '光学传感器',
    coreModel: 'BH1750',
    manufacturer: 'ROHM',
    interfaces: [InterfaceType.I2C],
    tags: ['光照传感器'],
    shelfNumber: 'B-33',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-034',
    name: 'HC-SR04 超声波测距模块',
    category: DeviceCategory.SENSOR,
    subCategory: '超声波传感器',
    coreModel: 'HC-SR04',
    manufacturer: '普通',
    interfaces: [InterfaceType.GPIO],
    tags: ['测距模块', '超声波'],
    purpose: '距离测量',
    project: '避障小车',
    shelfNumber: 'B-34',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-035',
    name: 'HC-SR501 人体红外感应模块',
    category: DeviceCategory.SENSOR,
    subCategory: '人体感应传感器',
    coreModel: 'HC-SR501',
    manufacturer: '普通',
    interfaces: [InterfaceType.GPIO],
    tags: ['红外传感器', '人体感应'],
    purpose: '人体检测',
    project: '智能照明系统',
    shelfNumber: 'B-35',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-036',
    name: 'BMP280 高精度气压/温度传感器模块',
    category: DeviceCategory.SENSOR,
    subCategory: '压力传感器',
    coreModel: 'BMP280',
    manufacturer: 'Bosch',
    interfaces: [InterfaceType.I2C, InterfaceType.SPI],
    tags: ['气压传感器', '温度传感器', '高精度'],
    purpose: '气压海拔测量',
    project: '气象站项目',
    shelfNumber: 'B-36',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-037',
    name: 'ACS712 30A 电流检测模块',
    category: DeviceCategory.SENSOR,
    subCategory: '其他传感器',
    coreModel: 'ACS712-30A',
    manufacturer: 'Allegro',
    interfaces: [InterfaceType.ADC],
    tags: ['电流传感器', '功率监测'],
    purpose: '电流监测',
    project: '电源监控系统',
    shelfNumber: 'B-37',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-038',
    name: '雨滴/雨水检测传感器模块',
    category: DeviceCategory.SENSOR,
    subCategory: '雨滴传感器',
    coreModel: 'LM393',
    manufacturer: '普通',
    interfaces: [InterfaceType.GPIO, InterfaceType.ADC],
    tags: ['雨滴传感器', '液体检测', '模拟传感器'],
    purpose: '降雨检测',
    project: '智能灌溉系统',
    shelfNumber: 'B-38',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-039',
    name: 'MQ-4 甲烷天然气传感器模块',
    category: DeviceCategory.SENSOR,
    subCategory: '气体传感器',
    coreModel: 'MQ-4',
    manufacturer: '炜盛',
    interfaces: [InterfaceType.ADC],
    tags: ['可燃气体检测', '甲烷传感器'],
    purpose: '天然气泄漏检测',
    project: '燃气安全系统',
    shelfNumber: 'B-39',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-040',
    name: 'MQ-9 一氧化碳/可燃气体传感器模块',
    category: DeviceCategory.SENSOR,
    subCategory: '气体传感器',
    coreModel: 'MQ-9',
    manufacturer: '炜盛',
    interfaces: [InterfaceType.ADC],
    tags: ['一氧化碳检测', '可燃气体检测', '有害气体检测'],
    purpose: '一氧化碳泄漏检测',
    project: '安全监测系统',
    shelfNumber: 'B-40',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-041',
    name: 'GUVA-S12SD 紫外线传感器模块',
    category: DeviceCategory.SENSOR,
    subCategory: '紫外线传感器',
    coreModel: 'GUVA-S12SD',
    manufacturer: '普通',
    interfaces: [InterfaceType.ADC],
    tags: ['紫外线检测', '模拟传感器'],
    purpose: '紫外线强度监测',
    project: '环境监测系统',
    shelfNumber: 'B-41',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-042',
    name: 'TDS 水质检测传感器模块',
    category: DeviceCategory.SENSOR,
    subCategory: '其他传感器',
    coreModel: 'TDS-Meter',
    manufacturer: '普通',
    interfaces: [InterfaceType.ADC],
    tags: ['水质检测', '模拟传感器', '液体检测'],
    purpose: '水质TDS检测',
    project: '水质监测系统',
    shelfNumber: 'B-42',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-043',
    name: 'HX711 称重传感器模块 (含压力传感器)',
    category: DeviceCategory.SENSOR,
    subCategory: '其他传感器',
    coreModel: 'HX711',
    manufacturer: 'Avia',
    interfaces: [InterfaceType.GPIO],
    tags: ['称重传感器', '压力传感器', 'ADC模块'],
    purpose: '称重测量',
    project: '电子秤项目',
    shelfNumber: 'B-43',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-044',
    name: '柔性弯折传感器模块',
    category: DeviceCategory.SENSOR,
    subCategory: '其他传感器',
    coreModel: 'Flex-Sensor',
    manufacturer: '普通',
    interfaces: [InterfaceType.ADC],
    tags: ['弯折传感器', '模拟传感器'],
    purpose: '角度/弯曲检测',
    project: '手势识别手套',
    shelfNumber: 'B-44',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-045',
    name: 'TCS3200 颜色识别传感器模块',
    category: DeviceCategory.SENSOR,
    subCategory: '颜色传感器',
    coreModel: 'TCS3200',
    manufacturer: 'AMS',
    interfaces: [InterfaceType.GPIO],
    tags: ['颜色传感器', 'RGB传感器'],
    purpose: '颜色识别',
    project: '颜色分拣机',
    shelfNumber: 'B-45',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-046',
    name: 'SW-520D 倾斜/振动传感器模块',
    category: DeviceCategory.SENSOR,
    subCategory: '运动传感器',
    coreModel: 'SW-520D',
    manufacturer: '普通',
    interfaces: [InterfaceType.GPIO],
    tags: ['倾斜传感器', '振动检测', '数字传感器'],
    purpose: '倾斜角度检测',
    project: '倾倒报警装置',
    shelfNumber: 'B-46',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-047',
    name: 'ADXL345 三轴加速度传感器模块',
    category: DeviceCategory.SENSOR,
    subCategory: '加速度传感器',
    coreModel: 'ADXL345',
    manufacturer: 'ADI',
    interfaces: [InterfaceType.I2C, InterfaceType.SPI],
    tags: ['加速度传感器', '数字传感器', '运动检测'],
    purpose: '运动/加速度检测',
    project: '计步器项目',
    shelfNumber: 'B-47',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-048',
    name: 'HC-SR04 防水型超声波测距模块',
    category: DeviceCategory.SENSOR,
    subCategory: '超声波传感器',
    interfaces: [InterfaceType.GPIO],
    tags: ['超声波', '测距', '防水'],
    shelfNumber: 'C-08',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-049',
    name: 'US-100 超声波测距模块 (串口/电平)',
    category: DeviceCategory.SENSOR,
    subCategory: '超声波传感器',
    interfaces: [InterfaceType.UART, InterfaceType.GPIO],
    tags: ['超声波', '测距', '串口'],
    shelfNumber: 'C-09',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-050',
    name: 'AM312 人体感应传感器模块 (微型)',
    category: DeviceCategory.SENSOR,
    subCategory: '人体感应传感器',
    interfaces: [InterfaceType.GPIO],
    tags: ['人体感应', '红外', '微型'],
    shelfNumber: 'C-10',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-051',
    name: 'RCWL-0516 雷达人体感应模块 (微波)',
    category: DeviceCategory.SENSOR,
    subCategory: '人体感应传感器',
    interfaces: [InterfaceType.GPIO],
    tags: ['人体感应', '雷达', '微波'],
    shelfNumber: 'C-11',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-052',
    name: 'MS5611 高精度气压传感器模块',
    category: DeviceCategory.SENSOR,
    subCategory: '压力传感器',
    interfaces: [InterfaceType.I2C, InterfaceType.SPI],
    tags: ['气压', '压力', '高精度'],
    shelfNumber: 'C-12',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-053',
    name: 'MPX5700AP 绝对压力传感器模块',
    category: DeviceCategory.SENSOR,
    subCategory: '压力传感器',
    interfaces: [InterfaceType.ADC],
    tags: ['压力', '模拟量'],
    shelfNumber: 'C-13',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-054',
    name: 'YL-38 + YL-69 雨滴传感器模块',
    category: DeviceCategory.SENSOR,
    subCategory: '雨滴传感器',
    interfaces: [InterfaceType.ADC, InterfaceType.GPIO],
    tags: ['雨滴', '湿度', '模拟量'],
    shelfNumber: 'C-14',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-055',
    name: '电容式雨量传感器模块 (模拟量)',
    category: DeviceCategory.SENSOR,
    subCategory: '雨滴传感器',
    interfaces: [InterfaceType.ADC],
    tags: ['雨滴', '电容式', '模拟量'],
    shelfNumber: 'C-15',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-056',
    name: 'ML8511 紫外线传感器模块 (模拟量)',
    category: DeviceCategory.SENSOR,
    subCategory: '紫外线传感器',
    interfaces: [InterfaceType.ADC],
    tags: ['紫外线', '光照', '模拟量'],
    shelfNumber: 'C-16',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-057',
    name: 'VEML6070 紫外线传感器模块 (I2C)',
    category: DeviceCategory.SENSOR,
    subCategory: '紫外线传感器',
    interfaces: [InterfaceType.I2C],
    tags: ['紫外线', 'I2C', '数字量'],
    shelfNumber: 'C-17',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-058',
    name: 'TSL2561 光照/颜色传感器模块',
    category: DeviceCategory.SENSOR,
    subCategory: '颜色传感器',
    interfaces: [InterfaceType.I2C],
    tags: ['颜色', '光照', 'I2C'],
    shelfNumber: 'C-18',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-059',
    name: 'GY-33 颜色识别传感器模块 (TCS34725+LED)',
    category: DeviceCategory.SENSOR,
    subCategory: '颜色传感器',
    interfaces: [InterfaceType.UART, InterfaceType.I2C],
    tags: ['颜色', '识别', '串口'],
    shelfNumber: 'C-19',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-060',
    name: 'SW-18010P 振动传感器模块 (高灵敏)',
    category: DeviceCategory.SENSOR,
    subCategory: '运动传感器',
    interfaces: [InterfaceType.GPIO],
    tags: ['振动', '倾斜', '开关量'],
    shelfNumber: 'C-20',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-061',
    name: 'MPU6050 六轴陀螺仪加速度模块 (含DMP)',
    category: DeviceCategory.SENSOR,
    subCategory: '加速度传感器',
    interfaces: [InterfaceType.I2C],
    tags: ['加速度', '陀螺仪', '六轴'],
    shelfNumber: 'C-21',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'SENSOR-20260626-062',
    name: 'LIS3DH 三轴加速度传感器模块',
    category: DeviceCategory.SENSOR,
    subCategory: '加速度传感器',
    interfaces: [InterfaceType.I2C, InterfaceType.SPI],
    tags: ['加速度', 'I2C', 'SPI'],
    shelfNumber: 'C-22',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },

  // ===== 通信模块类 =====
  {
    id: 'COMM-20260626-001',
    name: 'CH340烧录模块',
    category: DeviceCategory.COMM,
    subCategory: 'USB通信模块',
    coreModel: 'CH340',
    manufacturer: '沁恒',
    interfaces: [InterfaceType.USB, InterfaceType.UART],
    tags: ['串口通信模块'],
    shelfNumber: 'C-01',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'COMM-20260626-002',
    name: 'ESP8266 WiFi 模块 (2.4G, 刷好杀手/克隆程序)',
    category: DeviceCategory.COMM,
    subCategory: 'WiFi模块',
    coreModel: 'ESP8266',
    manufacturer: 'Espressif',
    interfaces: [InterfaceType.UART],
    tags: ['串口通信模块'],
    shelfNumber: 'C-02',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'COMM-20260626-003',
    name: '中移 ML307R 4G Cat.1 通信模块 (全网通低功耗)',
    category: DeviceCategory.COMM,
    subCategory: '4G/5G模块',
    coreModel: 'ML307R',
    manufacturer: '中移物联',
    interfaces: [InterfaceType.UART, InterfaceType.USB],
    tags: ['4G模块', '串口通信模块'],
    shelfNumber: 'C-03',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'COMM-20260626-004',
    name: 'MFRC-522 RC522 RFID 射频 IC 卡感应模块',
    category: DeviceCategory.COMM,
    subCategory: 'RFID模块',
    coreModel: 'RC522',
    manufacturer: 'NXP',
    interfaces: [InterfaceType.SPI],
    tags: ['射频模块'],
    shelfNumber: 'C-04',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'COMM-20260626-005',
    name: 'FT232RL USB 转 TTL 模块',
    category: DeviceCategory.COMM,
    subCategory: 'USB通信模块',
    coreModel: 'FT232RL',
    manufacturer: 'FTDI',
    interfaces: [InterfaceType.USB, InterfaceType.UART],
    tags: ['串口通信模块', '烧录器'],
    shelfNumber: 'C-05',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'COMM-20260626-006',
    name: 'CP2102 USB 转 TTL 模块',
    category: DeviceCategory.COMM,
    subCategory: 'USB通信模块',
    coreModel: 'CP2102',
    manufacturer: 'Silicon Labs',
    interfaces: [InterfaceType.USB, InterfaceType.UART],
    tags: ['串口通信模块', '烧录器'],
    shelfNumber: 'C-06',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'COMM-20260626-007',
    name: 'ESP-01S WiFi 模块',
    category: DeviceCategory.COMM,
    subCategory: 'WiFi模块',
    coreModel: 'ESP8266EX',
    manufacturer: 'Espressif',
    interfaces: [InterfaceType.UART],
    tags: ['串口通信模块', '低功耗'],
    shelfNumber: 'C-07',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'COMM-20260626-008',
    name: 'ESP-12F WiFi 模块',
    category: DeviceCategory.COMM,
    subCategory: 'WiFi模块',
    coreModel: 'ESP8266',
    manufacturer: 'Espressif',
    interfaces: [InterfaceType.UART],
    tags: ['串口通信模块'],
    shelfNumber: 'C-08',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'COMM-20260626-009',
    name: 'SIM7600CE 4G通信模块',
    category: DeviceCategory.COMM,
    subCategory: '4G/5G模块',
    coreModel: 'SIM7600CE',
    manufacturer: 'SIMCom',
    interfaces: [InterfaceType.UART, InterfaceType.USB],
    tags: ['4G模块', 'GPS模块', '串口通信模块'],
    shelfNumber: 'C-09',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'COMM-20260626-010',
    name: 'Air724UG 4G Cat.1 模块',
    category: DeviceCategory.COMM,
    subCategory: '4G/5G模块',
    coreModel: 'Air724UG',
    manufacturer: '合宙',
    interfaces: [InterfaceType.UART, InterfaceType.USB],
    tags: ['4G模块', '串口通信模块'],
    shelfNumber: 'C-10',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'COMM-20260626-011',
    name: 'PN532 NFC RFID 模块',
    category: DeviceCategory.COMM,
    subCategory: 'RFID模块',
    coreModel: 'PN532',
    manufacturer: 'NXP',
    interfaces: [InterfaceType.I2C, InterfaceType.SPI, InterfaceType.UART],
    tags: ['射频模块', 'NFC模块'],
    shelfNumber: 'C-11',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'COMM-20260626-012',
    name: 'RDM6300 125KHz RFID 模块',
    category: DeviceCategory.COMM,
    subCategory: 'RFID模块',
    coreModel: 'RDM6300',
    manufacturer: '普通',
    interfaces: [InterfaceType.UART],
    tags: ['射频模块', '低频'],
    shelfNumber: 'C-12',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'COMM-20260626-013',
    name: 'SX1278 LoRa 无线通信模块 (433MHz)',
    category: DeviceCategory.COMM,
    subCategory: 'LoRa模块',
    coreModel: 'SX1278',
    manufacturer: 'Semtech',
    interfaces: [InterfaceType.SPI],
    tags: ['LoRa模块', '远距离通信', '射频模块'],
    purpose: '远距离低功耗通信',
    project: 'LoRa网关项目',
    shelfNumber: 'C-13',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'COMM-20260626-014',
    name: 'HC-05 蓝牙串口主从模块',
    category: DeviceCategory.COMM,
    subCategory: '蓝牙模块',
    coreModel: 'BC417',
    manufacturer: '普通',
    interfaces: [InterfaceType.UART],
    tags: ['蓝牙模块', '串口通信模块', '主从一体'],
    purpose: '蓝牙无线通信',
    project: '蓝牙遥控项目',
    shelfNumber: 'C-14',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'COMM-20260626-015',
    name: 'HC-06 蓝牙从机模块',
    category: DeviceCategory.COMM,
    subCategory: '蓝牙模块',
    coreModel: 'BC417',
    manufacturer: '普通',
    interfaces: [InterfaceType.UART],
    tags: ['蓝牙模块', '串口通信模块', '从机'],
    purpose: '蓝牙无线接收',
    project: '蓝牙数据采集',
    shelfNumber: 'C-15',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'COMM-20260626-016',
    name: 'NEO-6M GPS 定位模块 (有源天线)',
    category: DeviceCategory.COMM,
    subCategory: 'GPS模块',
    coreModel: 'NEO-6M',
    manufacturer: 'u-blox',
    interfaces: [InterfaceType.UART],
    tags: ['GPS模块', '定位模块', '串口通信模块'],
    purpose: '卫星定位',
    project: '车载定位追踪器',
    shelfNumber: 'C-16',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'COMM-20260626-017',
    name: 'W5500 以太网模块 (SPI转以太网)',
    category: DeviceCategory.COMM,
    subCategory: '以太网模块',
    coreModel: 'W5500',
    manufacturer: 'WIZnet',
    interfaces: [InterfaceType.SPI, InterfaceType.ETHERNET],
    tags: ['以太网模块', 'SPI接口', '网络模块'],
    purpose: '有线网络通信',
    project: '物联网网关',
    shelfNumber: 'C-17',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'COMM-20260626-018',
    name: 'CC2530 ZigBee 无线通信模块',
    category: DeviceCategory.COMM,
    subCategory: 'ZigBee模块',
    coreModel: 'CC2530',
    manufacturer: 'TI',
    interfaces: [InterfaceType.UART, InterfaceType.GPIO],
    tags: ['ZigBee模块', '无线传感器网络', '串口通信模块'],
    purpose: 'ZigBee组网通信',
    project: '智能家居传感网络',
    shelfNumber: 'C-18',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'COMM-20260626-019',
    name: 'TJA1050 CAN 总线收发器模块',
    category: DeviceCategory.COMM,
    subCategory: '其他通信',
    coreModel: 'TJA1050',
    manufacturer: 'NXP',
    interfaces: [InterfaceType.CAN, InterfaceType.GPIO],
    tags: ['CAN总线模块', '工业通信'],
    purpose: 'CAN总线通信',
    project: '车载通信系统',
    shelfNumber: 'C-19',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'COMM-20260626-020',
    name: 'PN7150 NFC 近场通信模块',
    category: DeviceCategory.COMM,
    subCategory: 'NFC模块',
    coreModel: 'PN7150',
    manufacturer: 'NXP',
    interfaces: [InterfaceType.I2C, InterfaceType.GPIO],
    tags: ['NFC模块', '近场通信', '射频模块'],
    purpose: 'NFC读写与支付',
    project: '门禁系统',
    shelfNumber: 'C-20',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'COMM-20260626-021',
    name: 'JDY-33 蓝牙模块 (BLE 5.2, 低功耗)',
    category: DeviceCategory.COMM,
    subCategory: '蓝牙模块',
    coreModel: 'JDY-33',
    manufacturer: '云间半导体',
    interfaces: [InterfaceType.UART],
    tags: ['蓝牙模块', 'BLE 5.2', '低功耗', '串口通信模块'],
    purpose: '低功耗蓝牙通信',
    project: '蓝牙传感器节点',
    shelfNumber: 'C-21',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'COMM-20260626-022',
    name: 'E32-433T20D LoRa 无线模块 (433MHz, 1W)',
    category: DeviceCategory.COMM,
    subCategory: 'LoRa模块',
    coreModel: 'E32-433T20D',
    manufacturer: '亿佰特',
    interfaces: [InterfaceType.UART],
    tags: ['LoRa模块', '远距离通信', '射频模块', '串口通信模块'],
    purpose: '远距离无线数传',
    project: '远程数据采集系统',
    shelfNumber: 'C-22',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'COMM-20260626-023',
    name: 'RA-01 SX1278 LoRa 模块 (SPI接口)',
    category: DeviceCategory.COMM,
    subCategory: 'LoRa模块',
    coreModel: 'SX1278',
    manufacturer: 'Semtech',
    interfaces: [InterfaceType.SPI],
    tags: ['LoRa模块', '射频模块', '远距离通信'],
    purpose: 'LoRa网关节点',
    project: '物联网通信网络',
    shelfNumber: 'C-23',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'COMM-20260626-024',
    name: 'ATGM336H GPS 定位模块 (BDS+GPS双模)',
    category: DeviceCategory.COMM,
    subCategory: 'GPS模块',
    coreModel: 'ATGM336H',
    manufacturer: '中科微',
    interfaces: [InterfaceType.UART],
    tags: ['GPS模块', '北斗模块', '定位模块', '串口通信模块'],
    purpose: '双模卫星定位',
    project: '轨迹记录仪',
    shelfNumber: 'C-24',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'COMM-20260626-025',
    name: 'L76K GPS 多模定位模块 (GPS+北斗+GLONASS)',
    category: DeviceCategory.COMM,
    subCategory: 'GPS模块',
    coreModel: 'L76K',
    manufacturer: '中科微',
    interfaces: [InterfaceType.UART, InterfaceType.I2C],
    tags: ['GPS模块', '多模定位', '串口通信模块'],
    purpose: '多星座定位',
    project: '无人机定位系统',
    shelfNumber: 'C-25',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'COMM-20260626-026',
    name: 'ENC28J60 以太网模块 (SPI转以太网)',
    category: DeviceCategory.COMM,
    subCategory: '以太网模块',
    coreModel: 'ENC28J60',
    manufacturer: 'Microchip',
    interfaces: [InterfaceType.SPI, InterfaceType.ETHERNET],
    tags: ['以太网模块', 'SPI接口', '网络模块'],
    purpose: '有线网络接入',
    project: '网络传感器节点',
    shelfNumber: 'C-26',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'COMM-20260626-027',
    name: 'DM9000 以太网模块 (16位并口)',
    category: DeviceCategory.COMM,
    subCategory: '以太网模块',
    coreModel: 'DM9000',
    manufacturer: 'Davicom',
    interfaces: [InterfaceType.GPIO, InterfaceType.ETHERNET],
    tags: ['以太网模块', '并口接口', '网络模块'],
    purpose: '高速以太网通信',
    project: '嵌入式网络终端',
    shelfNumber: 'C-27',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'COMM-20260626-028',
    name: 'E18-MS1-PCB ZigBee 模块 (2.4GHz)',
    category: DeviceCategory.COMM,
    subCategory: 'ZigBee模块',
    coreModel: 'CC2530',
    manufacturer: '亿佰特',
    interfaces: [InterfaceType.UART, InterfaceType.GPIO],
    tags: ['ZigBee模块', '无线传感器网络', '串口通信模块'],
    purpose: 'ZigBee自组网',
    project: '智能照明系统',
    shelfNumber: 'C-28',
    quantity: 0,
    damagedQuantity: 0,
    purchaseDate: '2026-06-26',
    storageDate: '2026-06-26',
    createdAt: now,
    updatedAt: now,
  },
  // ===== 通信模块类 (续) =====
  {
    id: 'COMM-20260626-029',
    name: 'E32-433T20S LoRa 无线模块 (433MHz, 100mW)',
    category: DeviceCategory.COMM,
    subCategory: 'LoRa模块',
    interfaces: [InterfaceType.UART],
    tags: ['LoRa', '433MHz', '无线'],
    shelfNumber: 'F-08',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'COMM-20260626-030',
    name: 'E22-900M LoRa 无线模块 (868/915MHz, 500mW)',
    category: DeviceCategory.COMM,
    subCategory: 'LoRa模块',
    interfaces: [InterfaceType.UART],
    tags: ['LoRa', '900MHz', '无线'],
    shelfNumber: 'F-09',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'COMM-20260626-031',
    name: 'BN-220 GPS 定位模块 (北斗+GPS双模)',
    category: DeviceCategory.COMM,
    subCategory: 'GPS模块',
    interfaces: [InterfaceType.UART],
    tags: ['GPS', '北斗', '定位'],
    shelfNumber: 'F-10',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'COMM-20260626-032',
    name: 'ATGM336H GPS+北斗双模定位模块',
    category: DeviceCategory.COMM,
    subCategory: 'GPS模块',
    interfaces: [InterfaceType.UART],
    tags: ['GPS', '北斗', '双模'],
    shelfNumber: 'F-11',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'COMM-20260626-033',
    name: 'ENC28J60 以太网模块 (SPI转以太网)',
    category: DeviceCategory.COMM,
    subCategory: '以太网模块',
    interfaces: [InterfaceType.SPI],
    tags: ['以太网', 'SPI', '网络'],
    shelfNumber: 'F-12',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'COMM-20260626-034',
    name: 'CH395Q 以太网模块 (SPI/UART转以太网)',
    category: DeviceCategory.COMM,
    subCategory: '以太网模块',
    interfaces: [InterfaceType.SPI, InterfaceType.UART],
    tags: ['以太网', 'SPI', '串口'],
    shelfNumber: 'F-13',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'COMM-20260626-035',
    name: 'EBYTE E180-ZG120A ZigBee 无线模块',
    category: DeviceCategory.COMM,
    subCategory: 'ZigBee模块',
    interfaces: [InterfaceType.UART],
    tags: ['ZigBee', '无线', '组网'],
    shelfNumber: 'F-14',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'COMM-20260626-036',
    name: 'DRF1609H ZigBee 无线模块 (ZigBee Pro)',
    category: DeviceCategory.COMM,
    subCategory: 'ZigBee模块',
    interfaces: [InterfaceType.UART],
    tags: ['ZigBee', '无线', 'Pro'],
    shelfNumber: 'F-15',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'COMM-20260626-037',
    name: 'HC-42 蓝牙5.0 串口模块',
    category: DeviceCategory.COMM,
    subCategory: '蓝牙模块',
    interfaces: [InterfaceType.UART],
    tags: ['蓝牙', '5.0', '串口'],
    shelfNumber: 'F-16',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'COMM-20260626-038',
    name: 'JDY-23 低功耗蓝牙模块 (BLE 4.2)',
    category: DeviceCategory.COMM,
    subCategory: '蓝牙模块',
    interfaces: [InterfaceType.UART],
    tags: ['蓝牙', 'BLE', '低功耗'],
    shelfNumber: 'F-17',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'COMM-20260626-039',
    name: 'CC1101 无线收发模块 (315/433MHz)',
    category: DeviceCategory.COMM,
    subCategory: '其他通信',
    interfaces: [InterfaceType.SPI],
    tags: ['无线', '433MHz', 'SPI'],
    shelfNumber: 'F-18',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'COMM-20260626-040',
    name: 'SIM800C GPRS/GSM 通信模块 (2G)',
    category: DeviceCategory.COMM,
    subCategory: '其他通信',
    interfaces: [InterfaceType.UART],
    tags: ['GPRS', 'GSM', '2G'],
    shelfNumber: 'F-19',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },

  // ===== 执行器类 =====
  {
    id: 'ACTUATOR-20260626-020',
    name: '5V 微型真空泵 (370气泵, 负压)',
    category: DeviceCategory.ACTUATOR,
    subCategory: '直流电机',
    interfaces: [InterfaceType.ADC],
    tags: ['真空泵', '微型', '负压'],
    shelfNumber: 'J-10',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'ACTUATOR-20260626-021',
    name: 'JGB37-520 直流减速电机 (带霍尔编码器)',
    category: DeviceCategory.ACTUATOR,
    subCategory: '直流电机',
    interfaces: [InterfaceType.GPIO],
    tags: ['直流', '减速', '编码器'],
    shelfNumber: 'J-11',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'ACTUATOR-20260626-022',
    name: '12V 4020 散热风扇模块',
    category: DeviceCategory.ACTUATOR,
    subCategory: '风扇模块',
    interfaces: [InterfaceType.ADC],
    tags: ['散热', '风扇', '12V'],
    shelfNumber: 'J-12',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'ACTUATOR-20260626-023',
    name: '5V 7015 散热风扇模块 (涡轮增压)',
    category: DeviceCategory.ACTUATOR,
    subCategory: '风扇模块',
    interfaces: [InterfaceType.ADC],
    tags: ['散热', '风扇', '涡轮'],
    shelfNumber: 'J-13',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'ACTUATOR-20260626-024',
    name: '12V 推拉式电磁铁 (长行程, 10mm)',
    category: DeviceCategory.ACTUATOR,
    subCategory: '电磁铁',
    interfaces: [InterfaceType.GPIO],
    tags: ['电磁铁', '推拉式', '12V'],
    shelfNumber: 'J-14',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'ACTUATOR-20260626-025',
    name: '5V 微型电磁铁 (吸盘式, 200g吸力)',
    category: DeviceCategory.ACTUATOR,
    subCategory: '电磁铁',
    interfaces: [InterfaceType.GPIO],
    tags: ['电磁铁', '吸盘式', '5V'],
    shelfNumber: 'J-15',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'ACTUATOR-20260626-026',
    name: '12V 常开型电磁阀 (水阀, 1/2寸)',
    category: DeviceCategory.ACTUATOR,
    subCategory: '电磁阀',
    interfaces: [InterfaceType.GPIO],
    tags: ['电磁阀', '水阀', '常开'],
    shelfNumber: 'J-16',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'ACTUATOR-20260626-027',
    name: '12V 微型电磁阀 (气阀, 2位3通)',
    category: DeviceCategory.ACTUATOR,
    subCategory: '电磁阀',
    interfaces: [InterfaceType.GPIO],
    tags: ['电磁阀', '气阀', '3通'],
    shelfNumber: 'J-17',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'ACTUATOR-20260626-028',
    name: '42HB47 步进电机 (NEMA17, 1.8度)',
    category: DeviceCategory.ACTUATOR,
    subCategory: '步进电机驱动',
    interfaces: [InterfaceType.GPIO],
    tags: ['步进', 'NEMA17', '电机'],
    shelfNumber: 'J-18',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'ACTUATOR-20260626-029',
    name: '12V 1030 扁平振动电机模块',
    category: DeviceCategory.ACTUATOR,
    subCategory: '振动电机',
    interfaces: [InterfaceType.ADC],
    tags: ['振动', '电机', '扁平'],
    shelfNumber: 'J-19',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'ACTUATOR-20260626-030',
    name: '1027 扁平振动电机模块 (手机振动器)',
    category: DeviceCategory.ACTUATOR,
    subCategory: '振动电机',
    interfaces: [InterfaceType.ADC],
    tags: ['振动', '扁平', '手机'],
    shelfNumber: 'J-20',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },

  // ===== 连接器类 =====
  {
    id: 'CONNECTOR-20260626-015',
    name: '2.54mm 40P 弯针排针 (单排, 90度)',
    category: DeviceCategory.CONNECTOR,
    subCategory: '排针',
    interfaces: [],
    tags: ['排针', '2.54', '弯针'],
    shelfNumber: 'I-10',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'CONNECTOR-20260626-016',
    name: '2.54mm 8P 排母 (单排)',
    category: DeviceCategory.CONNECTOR,
    subCategory: '排母',
    interfaces: [],
    tags: ['排母', '2.54', '单排'],
    shelfNumber: 'I-11',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'CONNECTOR-20260626-017',
    name: '2.54mm 20P 排母 (单排, 加高)',
    category: DeviceCategory.CONNECTOR,
    subCategory: '排母',
    interfaces: [],
    tags: ['排母', '2.54', '加高'],
    shelfNumber: 'I-12',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'CONNECTOR-20260626-018',
    name: '10cm 面包板线 (M-M, 40根套装)',
    category: DeviceCategory.CONNECTOR,
    subCategory: '面包板线',
    interfaces: [],
    tags: ['面包板线', '跳线', '公对公'],
    shelfNumber: 'I-13',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'CONNECTOR-20260626-019',
    name: '20cm 面包板线 (F-F, 40根套装)',
    category: DeviceCategory.CONNECTOR,
    subCategory: '面包板线',
    interfaces: [],
    tags: ['面包板线', '跳线', '母对母'],
    shelfNumber: 'I-14',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'CONNECTOR-20260626-020',
    name: 'IDC排线 16P (2.54mm间距, 母对母, 20cm)',
    category: DeviceCategory.CONNECTOR,
    subCategory: 'IDC排线',
    interfaces: [],
    tags: ['IDC', '排线', '16P'],
    shelfNumber: 'I-15',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'CONNECTOR-20260626-021',
    name: 'IDC排线 34P (2.54mm间距, 母对母, 30cm)',
    category: DeviceCategory.CONNECTOR,
    subCategory: 'IDC排线',
    interfaces: [],
    tags: ['IDC', '排线', '34P'],
    shelfNumber: 'I-16',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'CONNECTOR-20260626-022',
    name: 'TYPE-C 公头焊接板 (16P, 带CC电阻+E-Mark)',
    category: DeviceCategory.CONNECTOR,
    subCategory: 'TYPE-C连接器',
    interfaces: [],
    tags: ['TYPE-C', '公头', '焊接'],
    shelfNumber: 'I-17',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'CONNECTOR-20260626-023',
    name: 'TYPE-C 母座转接板 (24P, 全引脚引出)',
    category: DeviceCategory.CONNECTOR,
    subCategory: 'TYPE-C连接器',
    interfaces: [],
    tags: ['TYPE-C', '母座', '转接'],
    shelfNumber: 'I-18',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'CONNECTOR-20260626-024',
    name: '6P6C RJ11 电话线接口模块 (带滤波)',
    category: DeviceCategory.CONNECTOR,
    subCategory: 'RJ11连接器',
    interfaces: [],
    tags: ['RJ11', '电话线', '6P6C'],
    shelfNumber: 'I-19',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'CONNECTOR-20260626-025',
    name: 'RJ12 6P6C 连接器模块 (带线)',
    category: DeviceCategory.CONNECTOR,
    subCategory: 'RJ11连接器',
    interfaces: [],
    tags: ['RJ12', '6P6C', '带线'],
    shelfNumber: 'I-20',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'CONNECTOR-20260626-026',
    name: 'FPC连接器 (1.0mm间距, 12P, 下接)',
    category: DeviceCategory.CONNECTOR,
    subCategory: 'FPC连接器',
    interfaces: [],
    tags: ['FPC', '1.0mm', '12P'],
    shelfNumber: 'I-21',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'CONNECTOR-20260626-027',
    name: 'FPC连接器 (0.5mm间距, 24P, 上接)',
    category: DeviceCategory.CONNECTOR,
    subCategory: 'FPC连接器',
    interfaces: [],
    tags: ['FPC', '0.5mm', '24P'],
    shelfNumber: 'I-22',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'CONNECTOR-20260626-028',
    name: '3.5mm 音频公头焊接板 (立体声, 带螺丝端子)',
    category: DeviceCategory.CONNECTOR,
    subCategory: '音频接口',
    interfaces: [],
    tags: ['音频', '3.5mm', '公头'],
    shelfNumber: 'I-23',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'CONNECTOR-20260626-029',
    name: 'RCA 莲花头音频接口模块 (母座, 红白)',
    category: DeviceCategory.CONNECTOR,
    subCategory: '音频接口',
    interfaces: [],
    tags: ['音频', 'RCA', '莲花头'],
    shelfNumber: 'I-24',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'CONNECTOR-20260626-030',
    name: '2.54mm 40P 排针排母套装 (直针+排母)',
    category: DeviceCategory.CONNECTOR,
    subCategory: '排针排母',
    interfaces: [],
    tags: ['排针', '排母', '套装'],
    shelfNumber: 'I-25',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'CONNECTOR-20260626-031',
    name: '2.0mm 40P 排针排母套装 (精细间距)',
    category: DeviceCategory.CONNECTOR,
    subCategory: '排针排母',
    interfaces: [],
    tags: ['排针', '排母', '2.0mm'],
    shelfNumber: 'I-26',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'CONNECTOR-20260626-032',
    name: '2EDG 3.81mm 接线端子 (10对, 绿色)',
    category: DeviceCategory.CONNECTOR,
    subCategory: '接线端子',
    interfaces: [],
    tags: ['端子', '3.81mm', '绿色'],
    shelfNumber: 'I-27',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'CONNECTOR-20260626-033',
    name: 'DG127 2.54mm 接线端子 (10对, 可拼接)',
    category: DeviceCategory.CONNECTOR,
    subCategory: '接线端子',
    interfaces: [],
    tags: ['端子', '2.54mm', '可拼接'],
    shelfNumber: 'I-28',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'CONNECTOR-20260626-034',
    name: 'RJ45 以太网接口模块 (8P8C, 带屏蔽)',
    category: DeviceCategory.CONNECTOR,
    subCategory: '网络接口',
    interfaces: [],
    tags: ['RJ45', '以太网', '屏蔽'],
    shelfNumber: 'I-29',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'CONNECTOR-20260626-035',
    name: 'USB-A 公头焊接板 (90度弯脚)',
    category: DeviceCategory.CONNECTOR,
    subCategory: 'USB连接器',
    interfaces: [],
    tags: ['USB', '公头', 'A型'],
    shelfNumber: 'I-30',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },

  // ===== 灯模块类 =====
  {
    id: 'LIGHT-20260626-016',
    name: '5mm 蓝色 LED 灯珠 (100颗装)',
    category: DeviceCategory.LIGHT,
    subCategory: '指示灯模块',
    interfaces: [],
    tags: ['LED', '蓝色', '5mm'],
    shelfNumber: 'H-10',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'LIGHT-20260626-017',
    name: 'WS2812B 8位 RGB LED 条形模块 (直插)',
    category: DeviceCategory.LIGHT,
    subCategory: '全彩LED模块',
    interfaces: [InterfaceType.GPIO],
    tags: ['RGB', 'WS2812', '全彩'],
    shelfNumber: 'H-11',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'LIGHT-20260626-018',
    name: 'LCD2004 2004 LCD 液晶显示模块 (I2C)',
    category: DeviceCategory.LIGHT,
    subCategory: 'LCD模块',
    interfaces: [InterfaceType.I2C],
    tags: ['LCD', '2004', 'I2C'],
    shelfNumber: 'H-12',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'LIGHT-20260626-019',
    name: '1.3寸 OLED 显示模块 (SH1106, SPI)',
    category: DeviceCategory.LIGHT,
    subCategory: 'OLED模块',
    interfaces: [InterfaceType.SPI, InterfaceType.I2C],
    tags: ['OLED', 'SH1106', '1.3寸'],
    shelfNumber: 'H-13',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'LIGHT-20260626-020',
    name: 'TM1650 4位数码管显示模块 (I2C)',
    category: DeviceCategory.LIGHT,
    subCategory: '数码管模块',
    interfaces: [InterfaceType.I2C],
    tags: ['数码管', 'TM1650', 'I2C'],
    shelfNumber: 'H-14',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'LIGHT-20260626-021',
    name: '5V 650nm 绿色激光头模块',
    category: DeviceCategory.LIGHT,
    subCategory: '激光模块',
    interfaces: [],
    tags: ['激光', '绿色', '650nm'],
    shelfNumber: 'H-15',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'LIGHT-20260626-022',
    name: 'WS2812B 5050 RGB LED 灯条 (0.5米, 30灯, 防水)',
    category: DeviceCategory.LIGHT,
    subCategory: 'LED灯条',
    interfaces: [InterfaceType.GPIO],
    tags: ['RGB', '灯条', '防水'],
    shelfNumber: 'H-16',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'LIGHT-20260626-023',
    name: '5mm 黄色 LED 灯珠 (100颗装)',
    category: DeviceCategory.LIGHT,
    subCategory: 'LED灯珠',
    interfaces: [],
    tags: ['LED', '黄色', '5mm'],
    shelfNumber: 'H-17',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'LIGHT-20260626-024',
    name: '8x8 MAX7219 LED 点阵模块 (红色, 级联)',
    category: DeviceCategory.LIGHT,
    subCategory: 'LED点阵',
    interfaces: [InterfaceType.SPI],
    tags: ['LED', '点阵', 'MAX7219'],
    shelfNumber: 'H-18',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
  {
    id: 'LIGHT-20260626-025',
    name: 'TM1638 LED 数码管 + 按键显示模块 (8位)',
    category: DeviceCategory.LIGHT,
    subCategory: 'LED数码管',
    interfaces: [InterfaceType.GPIO],
    tags: ['数码管', 'TM1638', '按键'],
    shelfNumber: 'H-19',
    quantity: 0, damagedQuantity: 0, purchaseDate: '2026-06-26', storageDate: '2026-06-26', createdAt: now, updatedAt: now,
  },
]
